### ISSUE TITLE
Getting bin/cdirip: Permission denied Uncaught error in ./dcdib:66 message

### ISSUE THREAD

**Issue by warheat1990** [alex-free/dreamcast-cdi-burner#9]
I'm using Ubuntu 20.04 (under proxmox) and I've tried running dcdib using this command

`sudo ./dcdib '/home/Soul Calibur/Soul Calibur.cdi' /dev/sr1`

and I'm getting this error  
  
```
Dreamcast CDI Burner v1.0.8
By Alex Free

Info: Using explicitly specified CD burner device from second argument: /dev/sr1

Extracting /home/Soul Calibur/Soul Calibur.cdi...\n
./dcdib: line 66: bin/cdirip: Permission denied
Uncaught error in ./dcdib:66
```

Any idea why?

**Comment by alex-free** [comment]
I'm on Pop!OS which is pretty close to your system and it works. I think maybe this was caused by a permission issue while zipping the file. I have fixed the permissions and this new zip should also work for you. If it does I'll push out an update with the fix among other things.

![Screenshot from 2023-08-10 12-49-20](https://github.com/alex-free/dreamcast-cdi-burner/assets/72545918/4f11ec78-23fb-4f66-a0bd-06bbbe5373da)

[dcdib-1.0.8-x86_64-fixed-p.zip](https://github.com/alex-free/dreamcast-cdi-burner/files/12315396/dcdib-1.0.8-x86_64-fixed-p.zip)

**Comment by warheat1990** [comment]
I'm still getting the same error using the file you provided.

I've tried chmod 777 on all the files and logged in as root but still have the same Permission Denied from line 66

```
Size: 810826545       Blocks: 1583656    IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 791204      Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2009-02-26 22:40:17.000000000 +0000
Modify: 2009-02-26 22:40:17.000000000 +0000
Change: 2023-08-11 00:45:31.207596045 +0000
 Birth: -
```

**Comment by alex-free** [comment]
> I'm still getting the same error using the file you provided.
> 
> 
> 
> I've tried chmod 777 on all the files and logged in as root but still have the same Permission Denied from line 66

What happens if you cd into the dcdib folder and execute:

bin/cdirip

**Comment by warheat1990** [comment]
it works! Sorry it turns out I forgot to make all the file under the folder `bin` executable. I did that and it's now working. However, I have another issue where I'm getting error `Sorry, no CD/DVD/BD-Recorder or unsupported CD/DVD/BD-Recorder found on this target`

```
Dreamcast CDI Burner v1.0.8
By Alex Free

Info: Using explicitly specified CD burner device from second argument: /dev/sr1

Extracting /home/SoulCalibur/SoulCalibur.cdi...\n
CDIrip - (C) 2004 by DeXT/Lawrence Williams

Searching file: '/home/SoulCalibur/SoulCalibur.cdi'
Found image file. Opening...
This is a v3.5 image
Destination path: '/tmp/cdib.oVg'

Analyzing image...
Found 2 session(s)

Ripping image... (Press Ctrl-C at any time to exit)

Session 1 has 1 track(s)
Creating cuesheet...
Saving  Track:  1  Type: Audio/2352  Size: 302     LBA: 0

Session 2 has 1 track(s)
Saving  Track:  2  Type: Mode2/2336  Size: 346495  LBA: 11702   [ISO]

All done!
Good burnin'...

Burning /home/SoulCalibur/SoulCalibur.cdi...
Detected CDI Type: WAV Track 1
Cdrecord-ProDVD-ProBD-Clone 3.00 (x86_64-unknown-linux-gnu) Copyright (C) 1995-2010 Jrg Schilling
TOC Type: 0 = CD-DA
scsidev: '/dev/sr1'
devname: '/dev/sr1'
scsibus: -2 target: -2 lun: -2
Warning: Open by 'devname' is unintentional and not supported.
Linux sg driver version: 3.5.27
Using libscg version 'schily-0.9'.
SCSI buffer size: 64512
atapi: 1
Device type    : Removable CD-ROM
Version        : 5
Response Format: 2
Capabilities   :
Vendor_info    : 'QEMU    '
Identifikation : 'QEMU DVD-ROM    '
Revision       : '2.5+'
Device seems to be: Generic CD-ROM.
/home/tools/dcdib-1.0.8-x86_64/bin/cdrecord2: Sorry, no CD/DVD/BD-Recorder or unsupported CD/DVD/BD-Recorder found on this target.
Uncaught error in ./dcdib:79
```

Here's the output of `sudo lshw -class disk`, I'm using `/dev/sr1`

```
  *-cdrom
       description: DVD reader
       product: QEMU DVD-ROM
       vendor: QEMU
       physical id: 0.0.0
       bus info: scsi@1:0.0.0
       logical name: /dev/cdrom
       logical name: /dev/dvd
       logical name: /dev/sr0
       version: 2.5+
       capabilities: removable audio dvd
       configuration: ansiversion=5 status=nodisc
  *-disk
       description: SCSI Disk
       product: QEMU HARDDISK
       vendor: QEMU
       physical id: 0.0.0
       bus info: scsi@2:0.0.0
       logical name: /dev/sda
       version: 2.5+
       size: 64GiB (68GB)
       capabilities: 5400rpm gpt-1.00 partitioned partitioned:gpt
       configuration: ansiversion=5 guid=7c5dcafa-b8a3-4e63-9b76-76f9c1e1bfd0 logicalsectorsize=512 sectorsize=512
  *-cdrom
       description: DVD reader
       product: QEMU DVD-ROM
       vendor: QEMU
       physical id: 0.0.0
       bus info: scsi@3:0.0.0
       logical name: /dev/sr1
       version: 2.5+
       capabilities: removable audio dvd
       configuration: ansiversion=5 status=ready
     *-medium
          physical id: 0
          logical name: /dev/sr1
```

**Comment by warheat1990** [comment]
I believe this is proxmox issue with DVD-Drive passthrough, feel free to close it.

**Comment by alex-free** [comment]
> I believe this is proxmox issue with DVD-Drive passthrough, feel free to close it.

Interesting, what is the end goal here? To use this on windows? I'm actually about to start working on a windows version next.

The problem as far as I can tell with your setup is the cd drives are identifying as CD-ROM/DVD-ROM, like they are not capable of burning only reading. So then cdrecord thinks the drive can't write to discs only read them, so it fails to burn using that setup.

I'm not sure how to pass through the drive to where it comes up correctly using that exact setup. However I have used this in virtual box. If you setup the usb pass through correctly to a usb burner it does work that way.

**Comment by warheat1990** [comment]
I believe you are right, here's the comment from proxmox forum on similar issue

Are you using the Use physical CD/DVD Drive option? That one only supports discs with files on them ([ISO9660](https://en.wikipedia.org/wiki/ISO_9660)), not DVD or Blu-ray video or CD audio. There are a few threads on this forum about using [SATA passthrough](https://pve.proxmox.com/wiki/PCI(e)_Passthrough), [USB passthrough](https://pve.proxmox.com/wiki/USB_Devices_in_Virtual_Machines) (with a USB/SATA-converter), [SCSI device passthrough](https://forum.proxmox.com/threads/how-to-do-a-scsi-passthrough.111505/) and [iSCSI](https://pve.proxmox.com/wiki/Storage:_iSCSI) to get CD burning and video playback to work.

Mine is a SATA drive, not USB.
